config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'session/auth'
  root "users#new"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
# edit user profile


  get "/passwords", to: "users#passwords"
  put "/passwords", to: "user#passwords"
  get "/searchs", to: "users#search"
  get "/find_friends", to: "users#find_friends"
  delete "/friends", to: "users#friends"
  get "/users/list", to: "users#list"
  post "/add_friends", to: "users#add_friends"
  post "/likes", to: "users#likes"
  delete "/likes", to: "users#likes"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"



  get "auth/verify",to: "account_activations#verify"
  get "/sucessVerify",to: "account_activations#sucessVerify"
  get "/unVerify",to: "account_activations#unVerify"
  # get "/active", to: "users#active"

  get "/newsfeeds", to: "newsfeeds#index"
  get "/uploadimages", to: "images#new"
  get "/list_image", to: "newsfeeds#list_image"
  get "list_video", to: "newsfeeds#list_video"
  resources :images
  resources :newsfeed_demos


  resources :users do
    resources :posts, only: [:create, :edit, :show, :destroy]
    resources :images
  end
  resources :posts do
    resources :images, only: :create
  end

  resources :auths, only: [:edit]

  resources :comments
  resources :chats
  resources :activities, only: [:create, :show]
  resources :notifications, only: [:show]
  resources :languages, only: [:create, :update, :destroy]
  resources :videos



  # resources :users do
  #   resources :posts
  #   resources :add_friends
  #   resources :cities
  #   resources :countries
  #   resources :comments
  #   resources :chats
  #   resources :activities
  #   resources :notifications
  #   resources :newsfeeds
  #   resources :images
  # end

  # resources :posts do
  #   resources :images
  # end

  concern :commentable do
    resources :comments
  end
  resources :posts, concerns: :commentable

  # concern :likable do
  #   resources :likes
  # end
  # resources :posts, concerns: :likable

  # concern :trackable do
  #   resources :activities
  # end
  # resources :comments, concerns: :trackable
  # resources :add_friends, concerns: :trackable
  # resources :likes, concerns: :trackable
  # resources :notifications, concerns: :trackable
  # resources :posts, concerns: :trackable

  # concern :notifiable do
  #   resources :notifications
  # end
  # resources :comments, concerns: :notifiable
  # resources :add_friends, concerns: :notifiable
  # resources :likes, concerns: :notifiable
end

app/controllers/newsfeed_demos_controller.rb
class NewsfeedDemosController < ApplicationController
  before_action :set_newsfeed_demo, only: [:show, :edit, :update, :destroy]

  # GET /newsfeed_demos
  # GET /newsfeed_demos.json
  def index
    @newsfeed_demos = Post.all
  end

  # GET /newsfeed_demos/1
  # GET /newsfeed_demos/1.json
  def show
  end

  # GET /newsfeed_demos/new
  def new
    @newsfeed_demo = NewsfeedDemo.new
  end

  # GET /newsfeed_demos/1/edit
  def edit
  end

  # POST /newsfeed_demos
  # POST /newsfeed_demos.json
  def create
    @newsfeed_demo = NewsfeedDemo.new(newsfeed_demo_params)

    respond_to do |format|
      if @newsfeed_demo.save
        format.html { redirect_to @newsfeed_demo, notice: 'Newsfeed demo was successfully created.' }
        format.json { render :show, status: :created, location: @newsfeed_demo }
      else
        format.html { render :new }
        format.json { render json: @newsfeed_demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsfeed_demos/1
  # PATCH/PUT /newsfeed_demos/1.json
  def update
    respond_to do |format|
      if @newsfeed_demo.update(newsfeed_demo_params)
        format.html { redirect_to @newsfeed_demo, notice: 'Newsfeed demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsfeed_demo }
      else
        format.html { render :edit }
        format.json { render json: @newsfeed_demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsfeed_demos/1
  # DELETE /newsfeed_demos/1.json
  def destroy
    @newsfeed_demo.destroy
    respond_to do |format|
      format.html { redirect_to newsfeed_demos_url, notice: 'Newsfeed demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsfeed_demo
      @newsfeed_demo = NewsfeedDemo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsfeed_demo_params
      params.fetch(:newsfeed_demo, {})
    end
end

app/helpers/newsfeed_demos_helper.rb
module NewsfeedDemosHelper
end

app/views/newsfeed_demos/_form.html.erb
<%= form_with(model: newsfeed_demo, local: true) do |form| %>
  <% if newsfeed_demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsfeed_demo.errors.count, "error") %> prohibited this newsfeed_demo from being saved:</h2>

      <ul>
      <% newsfeed_demo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newsfeed_demos/edit.html.erb
<h1>Editing Newsfeed Demo</h1>

<%= render 'form', newsfeed_demo: @newsfeed_demo %>

<%= link_to 'Show', @newsfeed_demo %> |
<%= link_to 'Back', newsfeed_demos_path %>

app/views/newsfeed_demos/index.html.erb
<div class="" id="page-contents">
<p id="notice"><%= notice %></p>
    <div class="container">
      <div class="row">

        <!-- Newsfeed Common Side Bar Left
        ================================================= -->
        <div class="col-md-3 static">
          <%= render "partials/newsfeed_left" %>
        </div>
        <!-- END Newsfeed Common Side Bar Left
        ================================================= -->


        <!-- Newsfeed Contents
        ================================================= -->
        <div class="col-md-7">

          <!-- Post Create Box
          ================================================= -->
          <div class="create-post">
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <div class="form-group">
                  <img src="http://placehold.it/300x300" alt="" class="profile-photo-md" />
                  <textarea name="texts" id="exampleTextarea" cols="50" rows="5" class="form-control" placeholder="Write what you wish"></textarea>
                </div>
              </div>
              <div class="col-md-12 col-sm-12">
                <div class="tools">
                  <ul class="publishing-tools list-inline">
                    <li><a href="#"><i class="icon images"></i></a></li>
                    <li><a href="#"><i class="icon video"></i></a></li>
                  </ul>
                  <button class="btn-primary pull-right btn">Publish</button>
                </div>
            </div>
          </div>
          <div class="col-md-12 col-sm-12">
            <div class="tools">
              <ul class="publishing-tools list-inline">
                <li><a href="#"><i class="icon images"></i></a></li>
                <li><a href="#"><i class="icon video"></i></a></li>
              </ul>
              <button class="btn-primary pull-right btn">Publish</button>
            </div>
          </div>
        </div>
      </div><!-- Post Create Box End-->
    <!-- Newsfeed Contents
    ================================================= -->
      <%= render "partials/post_1" %>
      <%= render "partials/post_2" %>
      <%= render "partials/post_3" %>
    <!-- END Newsfeed Contents
    ================================================= -->
    </div>
    <div class="col-md-2">

    </div>
</div>

app/views/newsfeed_demos/new.html.erb
<h1>New Newsfeed Demo</h1>

<%= render 'form', newsfeed_demo: @newsfeed_demo %>

<%= link_to 'Back', newsfeed_demos_path %>

app/views/newsfeed_demos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_newsfeed_demo_path(@newsfeed_demo) %> |
<%= link_to 'Back', newsfeed_demos_path %>