config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'session/auth'
  root "users#new"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
# edit user profile


  get "/passwords", to: "users#passwords"
  put "/passwords", to: "user#passwords"
  get "/searchs", to: "users#search"
  get "/find_friends", to: "users#find_friends"
  delete "/friends", to: "users#friends"
  get "/users/list", to: "users#list"
  post "/add_friends", to: "users#add_friends"
  post "/likes", to: "users#likes"
  delete "/likes", to: "users#likes"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"



  get "auth/verify",to: "account_activations#verify"
  get "/sucessVerify",to: "account_activations#sucessVerify"
  get "/unVerify",to: "account_activations#unVerify"
  # get "/active", to: "users#active"

  get "/newsfeeds", to: "newsfeeds#index"
  get "/uploadimages", to: "images#new"
  get "/list_image", to: "newsfeeds#list_image"
  get "list_video", to: "newsfeeds#list_video"
  resources :images
  resources :newsfeed_demos


  resources :users do
    resources :posts, only: [:create, :edit, :show, :destroy]
    resources :images
  end
  resources :posts do
    resources :images, only: :create
  end

  resources :auths, only: [:edit]

  resources :comments
  resources :chats
  resources :activities, only: [:create, :show]
  resources :notifications, only: [:show]
  resources :languages, only: [:create, :update, :destroy]
  resources :videos



  # resources :users do
  #   resources :posts
  #   resources :add_friends
  #   resources :cities
  #   resources :countries
  #   resources :comments
  #   resources :chats
  #   resources :activities
  #   resources :notifications
  #   resources :newsfeeds
  #   resources :images
  # end

  # resources :posts do
  #   resources :images
  # end

  concern :commentable do
    resources :comments
  end
  resources :posts, concerns: :commentable

  # concern :likable do
  #   resources :likes
  # end
  # resources :posts, concerns: :likable

  # concern :trackable do
  #   resources :activities
  # end
  # resources :comments, concerns: :trackable
  # resources :add_friends, concerns: :trackable
  # resources :likes, concerns: :trackable
  # resources :notifications, concerns: :trackable
  # resources :posts, concerns: :trackable

  # concern :notifiable do
  #   resources :notifications
  # end
  # resources :comments, concerns: :notifiable
  # resources :add_friends, concerns: :notifiable
  # resources :likes, concerns: :notifiable
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[show edit update destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show; end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit; end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params.fetch(:notification, {})
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>