config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'session/auth'
  root "users#new"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
# edit user profile


  get "/passwords", to: "users#passwords"
  put "/passwords", to: "user#passwords"
  get "/searchs", to: "users#search"
  get "/find_friends", to: "users#find_friends"
  delete "/friends", to: "users#friends"
  get "/users/list", to: "users#list"
  post "/add_friends", to: "users#add_friends"
  post "/likes", to: "users#likes"
  delete "/likes", to: "users#likes"

  get "/registration", to: "users#new"
  post "/registration", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"



  get "auth/verify",to: "account_activations#verify"
  get "/sucessVerify",to: "account_activations#sucessVerify"
  get "/unVerify",to: "account_activations#unVerify"
  # get "/active", to: "users#active"

  get "/newsfeeds", to: "newsfeeds#index"
  get "/uploadimages", to: "images#new"
  get "/list_image", to: "newsfeeds#list_image"
  get "list_video", to: "newsfeeds#list_video"
  resources :images
  resources :newsfeed_demos


  resources :users do
    resources :posts, only: [:create, :edit, :show, :destroy]
    resources :images
  end
  resources :posts do
    resources :images, only: :create
  end

  resources :auths, only: [:edit]

  resources :comments
  resources :chats
  resources :activities, only: [:create, :show]
  resources :notifications, only: [:show]
  resources :languages, only: [:create, :update, :destroy]
  resources :videos



  # resources :users do
  #   resources :posts
  #   resources :add_friends
  #   resources :cities
  #   resources :countries
  #   resources :comments
  #   resources :chats
  #   resources :activities
  #   resources :notifications
  #   resources :newsfeeds
  #   resources :images
  # end

  # resources :posts do
  #   resources :images
  # end

  concern :commentable do
    resources :comments
  end
  resources :posts, concerns: :commentable

  # concern :likable do
  #   resources :likes
  # end
  # resources :posts, concerns: :likable

  # concern :trackable do
  #   resources :activities
  # end
  # resources :comments, concerns: :trackable
  # resources :add_friends, concerns: :trackable
  # resources :likes, concerns: :trackable
  # resources :notifications, concerns: :trackable
  # resources :posts, concerns: :trackable

  # concern :notifiable do
  #   resources :notifications
  # end
  # resources :comments, concerns: :notifiable
  # resources :add_friends, concerns: :notifiable
  # resources :likes, concerns: :notifiable
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :post, :optional => true

  mount_uploader :video, VideoUploader
  # validates_attachment_size( :in => 1..1.megabyte)
  # validates_attachment_content_type :video, :content_type => ['application/x-shockwave-flash', 'application/x-shockwave-flash', 'application/flv', 'video/x-flv']
  # has_attached_file :video,
  #   processors: [:ffmpeg],
  #     :size => { :in => 0..25.megabytes }
  validates :video, presence: true, file_size: { less_than: 20.megabytes }

  private
  def self.findByVideoAndId(id)
    self.where(post_id: id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /videos
  # GET /videos.json
  def index
    @post = current_user.posts.all
    video = Video.all.where(videos: { user_id: current_user.id })
    @post_videos = video.joins("INNER JOIN posts ON videos.post_id = posts.id")
    render json: {post: @post, video: @post_videos}
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    id_post = @video.post_id
    @post_video = Post.find(id_post)
    render json: {post: @post_video, video: @video,  user: current_user}
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
      if @video.save
        render json: @video, status: :created
      else
        render json: @video.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    # video_params = {
    #   user_id: current_user.id,
    #   post_id: 1,
    #   video: params[:video]
    # }
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
      def set_video
        @video = Video.find(params[:id])
      end
      # Never trust parameters from the scary internet, only allow the white list through.
      def video_params
          video_Params = {
             user_id: current_user.id,
             post_id: nil,
             video: params[:video]
           }
      end
end

app/helpers/videos_helper.rb
# frozen_string_literal: true

module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, html: {multipart: true} do |f| %>
<div class="tool">
  <ul class="publishing-tools list-inline">
    <%= f.file_field :video, name: "video[]", class: "post_image" %>
    <%= f.button "Submit", class: "btn btn-primary pull-right", id: "btn-upload" %>
  </ul>
</div>
<% end %>

app/views/videos/_video.html.erb
<script>
$(function() {
        getVideos();
  });
   function getVideos() {
    $.ajax({
      type: "get",
      url: '/videos',
      dataType: 'json',
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'), // Optional
        'Content-Type': 'application/json'
      },
      success: function(videos) {
        var html = '';
        for (var video of videos.video){
            html += ' <div class="grid-item col-md-6 col-sm-6">';
            html += '   <div class="media-grid">'; 
            html += '     <div class="video-wrapper" data-toggle="modal" data-target=".modal-'+video.id+'">';  
            html += '     <video controls><source src="'+video.video.url+'" type="video/mp4" class="post_video"  data-vdid="' + video.id + '" data-postid="'+video.post_id+'"></video>';             
            html += '     </div>';
            html += '     <div class="modal fade modal-'+video.id+'" tabindex="-1" role="dialog" aria-hidden="true">';
            html += '       <div class="modal-dialog modal-lg">';
            html += '         <div class="modal-content">';
            html += '         </div>';
            html += '       </div>';
            html += '     </div>';
            html += '   </div>';
            html += ' </div>';
        }
        $('.js-masonry').append(html);
        $('.video-wrapper').bind('click',function(){
            var vid_id = $(this).find('.post_video').data('vdid');
            var video_post_id = $(this).find('.post_video').data('postid');
            $.ajax({
                        type: "get",
                        url: '/videos/'+vid_id,
                        dataType: 'json',
                        headers: {
                          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'), // Optional
                          'Content-Type': 'application/json'
                        },
                        success: function(vidpost) {
                          console.log(vidpost.post.id);
                          var html1 = '';
                          if(vidpost.post.id == video_post_id){
                          html1 += '           <div class="post-content box1">';
                          html1 += '             <div class="box2">';
                          html1 += '               <div class="post-container">';
                          html1 += '                 <img src="http://placehold.it/300x300" alt="user" class="profile-photo-md pull-left" />';
                          html1 += '                 <div class="row post-detail">';
                          html1 += '                   <div class="col-md-10 user-info">';
                          html1 += '                     <h5><a href="timeline.html" class="profile-link">'+vidpost.user.first_name+'</a> <span class="following">following</span></h5>';
                          html1 += '                     <p class="text-muted">Published a photo about 3 mins ago</p>';
                          html1 += '                   </div>';
                          html1 += '                   <div class="col-md-2 reaction">';
                          html1 += '                     <div class="dropdown" style="float:right;">';
                          html1 += '                       <a class="dropbtn">...</a>';
                          html1 += '                       <div class="dropdown-content">';
                          html1 += '                        <a class="deletePost" data-postid="' + vidpost.post.id + '">Delete</a>';
                          html1 += '                       </div>';
                          html1 += '                     </div>';
                          html1 += '                   </div>';
                          html1 += '                 </div>';
                          html1 += '                 <div class="post-text">';
                          html1 += '                   <p>'+vidpost.post.context+' <i class="em em-anguished"></i> <i class="em em-anguished"></i> <i class="em em-anguished"></i></p>';
                          html1 += '                 </div>';
                          html1 += '               </div>';
                          html1 += '               <video class="post-video" controls> <source src="'+ vidpost.video.video.url +'" type="video/mp4"> </video> ';
                          html1 += '               <div class="line-divider" ></div>';
                          html1 += '               <div class="row">';
                          html1 += '                 <div class="col-md-2 reaction">';
                          html1 += '                   <a href="#" class="btn text-like">'+vidpost.post.like_count+' <i class="icon heart"></i>Like</a>';
                          html1 += '                 </div>';
                          html1 += '                 <div class="col-md-6">';
                          html1 += '                 </div>';
                          html1 += '                 <div class="col-md-2 reaction">';
                          html1 += '                   <a href="#" class="btn text-black">'+vidpost.post.comments_count+' <i class="icon comment"></i>Comment</a>';
                          html1 += '                 </div>';
                          html1 += '               </div>';
                          html1 += '               <div class="line-divider" style="margin-top: 4px;"></div>'; 
                          html1 += '               <a  class="addloadcomment" style="padding-left: 8px;" >Load more comment</a>';
                          html1 += '             </div> ';
                          html1 += '             <div class="box3">   ';
                          html1 += '               <div class="row comment-box post-container">';
                          html1 += '                 <div class="col-md-1.5 comment-avatar">';
                          html1 += '                   <img src="http://placehold.it/300x300" alt="user" class="profile-photo-sm pull-left" />';
                          html1 += '                 </div>';
                          html1 += '                 <div class="col-md-10 comment-content">';
                          html1 += '                   <div class="post-comment">';
                          html1 += '                     <div class="dropdown" style="float:right;">';
                          html1 += '                       <a class="dropbtn">...</a>';
                          html1 += '                       <div class="dropdown-content">';
                          html1 += '                         <a href="#">Sửa</a>';
                          html1 += '                         <a href="#">Delete</a>';
                          html1 += '                       </div>';
                          html1 += '                     </div>';
                          html1 += '                     <a href=""class="profile-link"><h5>John</h5></a><p style= "padding-right: 4px;">comment 1 1223213Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mi <i class="em em-anguished"></i> <i class="em em-anguished"></i> <i class="em em-anguished"></i></p>';
                          html1 += '                   </div>';
                          html1 += '                 </div>';
                          html1 += '               </div>';
                          html1 += '               <div class="post-container">';
                          html1 += '                 <div class="row">';
                          html1 += '                   <div class="col-md-1.5"  style="margin-left: 12px;margin-right: 5px">';
                          html1 += '                     <img src="http://placehold.it/300x300" alt="user" class="profile-photo-sm pull-left" />';
                          html1 += '                   </div>';
                          html1 += '                   <div class="col-md-10" style="padding-left: 0px;padding-top: 15px;">';  
                          html1 += '                     <textarea type="texts" cols="5" rows="1" class="form-control" placeholder="Post a comment" style="line-height: 15px; border-radius: 10px"></textarea>';
                          html1 += '                     <button type="button" name="button" class="btn btn-primary" style="float: right; margin-top:5px;">Sent</button>';
                          html1 += '                   </div>';
                          html1 += '                 </div>';
                          html1 += '               </div>';
                          html1 += '             </div>  ';
                          html1 += '           </div>';
                          $('.modal-content').html(html1);
                          }
                        }
                        })
          });
      }
    })
  }
</script>



  <div class="col-md-7 images_show">
    <h4 style="padding-bottom:10px;"><i class="icon images"></i>videos</h4>
    <div class="line-divider" style="border-top: 1px solid #ccc3c3;margin-bottom: 16px;" ></div>
    <div class="media">
      <div class="row js-masonry" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": ".grid-sizer", "percentPosition": true }'>
      </div>
    </div>
    <div class="line-divider" style="border-top: 1px solid #ccc3c3;margin-bottom: 16px;" ></div>
  </div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <!-- Newsfeed Common Side Bar Left
  ================================================= -->
  <div class="col-md-3 static">
    <%= render "partials/newsfeed_left" %>
  </div>
  <!-- END Newsfeed Common Side Bar Left
  ================================================= -->

  <!-- Newsfeed Contents
  ================================================= -->
  <div class="col-md-7">
    <!-- Media content
    ================================================= -->
      <h4 style="padding-bottom:10px;"><i class="icon film"></i>Videos</h4>
      <div class="line-divider" style="border-top: 1px solid #ccc3c3;margin-bottom: 16px;" ></div>

      <div class="media">
        <div class="row js-masonry" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": ".grid-sizer", "percentPosition": true }'>
          <!-- <div class="grid-sizer col-md-6 col-sm-6"></div> -->
        <!-- list video -->
          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-1">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-1" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_2" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>

          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-2">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-2" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_1" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>
          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-1">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-1" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_3" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>
          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-1">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-1" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_2" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>
          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-1">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-1" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_2" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>
          <div class="grid-item col-md-6 col-sm-6">
            <div class="media-grid">
              <div class="img-wrapper" data-toggle="modal" data-target=".modal-3">
                <video controls>
                  <source src="videos/1.mp4" type="video/mp4">
                </video>
              </div>
              <div class="media-info">
                <div class="reaction">
                  <a href="#" class="btn text-like"><i class="icon heart"></i> 46</a>
                  <a href="#" class="btn text-black"><i class="icon comment"></i> 11</a>
                </div>

              </div>

              <!--Popup-->
              <div class="modal fade modal-3" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <%= render "partials/post_3" %>

                  </div>
                </div>
              </div><!--Popup End-->

            </div>
          </div>
        <!-- end list video -->
        </div>
      </div>
      <div class="line-divider" style="border-top: 1px solid #ccc3c3;margin-bottom: 16px;" ></div>

    <!-- Media
    ================================================= -->
  </div>
    <%= render "partials/newsfeed_right" %>
</div>

app/views/videos/new.html.erb
<%= render 'form' %>
<script>
    $(document).ready(function(){

        $("#btn-upload").click(function(e){
        e.preventDefault();
        var fd = new FormData();
        var files = $('#video_video')[0].files[0];

            fd.append('video', files);
            $.ajax({
                url: '/videos',
                dataType: 'json',
                type: 'post',
                data: fd,
                contentType: false,
                processData: false,
                success: function(vid){
                    console.log(vid);
                },
            });
        });
    });
</script>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>

  <%= @video.video %><br>
  <%= video_tag @video.video_url.to_s, controls: true %>

</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>